# -*- mode: ruby -*-
# vi: set ft=ruby :

# Esempio Vagrantfile 
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 8080, host_ip: "127.0.0.1"
end
