# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.
  config.vm.box = "geerlingguy/centos8"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.linked_clone = true
  end

  # Application host 1.
  config.vm.define "host1" do |host|
    host.vm.hostname = "host1"
    host.vm.network :private_network, ip: "192.168.60.4"
  end

  # Application host 2.
  config.vm.define "host2" do |host|
    host.vm.hostname = "host2"
    host.vm.network :private_network, ip: "192.168.60.5"
  end
end
